services:
  database:
    image: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    env_file:
      - .env
    depends_on:
      - database
    ports:
      - "3000:3000"

  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    env_file:
      - .env
    depends_on:
      - backend
    ports:
      - "80:3000"

volumes:
  db_data:
