name: Docker Publish

on:
    push:
        tags:
            - '*'

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Check out code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  ref: ${{ github.event.repository.default_branch }}

            - name: Bump package version
              run: node .github/actions/bump-package-version.js
              env:
                  VERSION: ${{ github.ref_name }}

            - name: Push package change
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  branch: ${{ github.event.repository.default_branch }}
                  commit_message: 'chore: bump package version to ${{ github.ref_name }}'
                  commit_user_name: Package Bumper
                  commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
                  file_pattern: package.json

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push (backend)
              uses: docker/build-push-action@v3
              with:
                  context: .
                  file: ./apps/backend/Dockerfile
                  push: true
                  tags: |
                      borisnl/yar-backend:${{ github.ref_name }}
                      borisnl/yar-backend:latest

            - name: Build and push (web)
              uses: docker/build-push-action@v3
              with:
                  context: .
                  file: ./apps/web/Dockerfile
                  push: true
                  tags: |
                      borisnl/yar-web:${{ github.ref_name }}
                      borisnl/yar-web:latest
