name: Docker Publish

on:
    push:
        tags:
            - '*'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v3

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Bump package version
              run: node .github/actions/bump-package-version.js
              env:
                  VERSION: ${{ github.ref_name }}

            - name: Push manifest change
              uses: EndBug/add-and-commit@v9
              with:
                  add: package.json
                  push: true
                  message: 'chore: bump package version to ${{ github.ref_name }}'

            - name: Build and push (backend)
              uses: docker/build-push-action@v3
              with:
                  context: .
                  file: ./apps/backend/Dockerfile
                  push: true
                  tags: |
                      borisnl/yar-backend:${{ github.ref_name }}
                      borisnl/yar-backend:latest

            - name: Build and push (web)
              uses: docker/build-push-action@v3
              with:
                  context: .
                  file: ./apps/web/Dockerfile
                  push: true
                  tags: |
                      borisnl/yar-web:${{ github.ref_name }}
                      borisnl/yar-web:latest
